# Generated by Django 5.1.1 on 2024-09-30 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('givenname', models.CharField(max_length=255)),
                ('middleinitial', models.CharField(max_length=3)),
                ('lastname', models.CharField(max_length=255)),
            ],
        ),
    ]
