# Generated by Django 5.1.1 on 2024-09-30 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_rename_givenname_member_givenname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='bio1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='member',
            name='chem1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='member',
            name='cs3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='member',
            name='eng3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='member',
            name='fil3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='member',
            name='math3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='member',
            name='phys1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='member',
            name='ss3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='member',
            name='stat',
            field=models.BooleanField(default=False),
        ),
    ]
